# Generated by Django 3.2.4 on 2021-06-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_spend_payer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(help_text='Payer name', max_length=255, verbose_name='payer')),
                ('points', models.IntegerField(help_text='Points', verbose_name='points')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
